import type { NextPage } from 'next'
import Head from 'next/head'
import Router from 'next/router'

const Home: NextPage = ({ user }: any) => {
  return (
    <div>
      <Head>
        <title>URL Shortener</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="jumbotron jumbotron-fluid mt-5 bg-light p-5">
        <div className="container">
          <h1 className="display-4">Welcome, Kisa.lt!</h1>
          <p className="lead">Create short urls by Kisa.lt</p>
          <hr className="my-4" />
          <p>Now Signup and start creating short urls.</p>
          {
            user ? <p className="lead">
              <a
                onClick={() => Router.push('/urls/create')}
                className="btn btn-primary btn-lg" role="button">Create Url</a>
            </p>
              :
              <p className="lead">
                <a
                  onClick={() => Router.push('/auth/login')}
                  className="btn btn-primary btn-lg" role="button">Sign In</a>
              </p>
          }
        </div>
      </div>
    </div>
  )
}

export default Home
